# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='days_from_sowing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farmerdata',
            name='bill',
            field=models.CharField(max_length=50),
        ),
    ]
